# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8dcad35ecdc145c544bf1d28b55c3e1e5ee2b09b814f083eaba9dc3c1730cca64e8b21d5c05aa9d8b4ba3eec381d1e5d7239b297695ceb3c6a59e795d05e3daa

test:
  secret_key_base: a4c76c4d0d56985bb8eb2c2623e509d02a781ed0e2c34ac4a687b0e6fbff50d4ba6b973380495140933c4d26d24307707c92188f434c243dff36137a7ace5980

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
